  - name: Remove k8s head node
    local_action:
      module: cs_instance
      name: "{{ k8s_node_prefix }}-head"
      state: absent

  - name: Remove k8s nodes
    local_action:
      module: cs_instance
      name: "{{ k8s_node_prefix }}-node-{{ item }}"
      state: absent
    with_sequence: count={{ k8s_num_nodes }}
